name: Create Release
on:
  workflow_dispatch:
    inputs:
      Version:
        description: "Version to be released in format: x.y.z, where x => major version, y => minor version and z => patch version, Current is: 0.1.1"
        required: true
        default: "0.1.1"
      Title:
        description: "Title of the release"
        required: true
        default: "Releasing fixes for bugs"
jobs:
  create-release:
    runs-on: ubuntu-latest
    environment: 'Production'
    steps:
      - uses: actions/checkout@v3
      
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          include: ${{ github.event.inputs.Version }}
      
      - name: Show Tag
        id: display
        run: |
          echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'
      
      - name: Create Tag 
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ github.event.inputs.Version }}
          tag_prefix: ""
          
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ github.event.inputs.Title }}
          body: ${{ steps.tag_version.outputs.changelog }}
