name: Create Release
on:
  workflow_dispatch:
    inputs:
      Version:
        description: "Version to be released in format: x.y.z, where x => major version, y => minor version and z => patch version, Current is: 0.1.1"
        required: true
        default: "0.1.1"
      Title:
        description: "Title of the release"
        required: true
        default: "Releasing fixes for bugs"
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ github.event.inputs.Version }}
          tag_prefix: ""
          
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ github.event.inputs.Title }}
          body: ${{ steps.tag_version.outputs.changelog }}
