name: Create/update tag
on:
  workflow_dispatch:
    inputs:
      Version:
        description: "Version to be released in format: x.y.z, where x => major version, y => minor version and z => patch version, Current is: 0.1.1"
        required: true
        default: "0.1.1"
      Title:
        description: "Title of the release"
        required: true
        default: "Releasing fixes for bugs"
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ github.event.inputs.Version }}
          message: ${{ github.event.inputs.Title }}
